### ISSUE TITLE
Allowing for DOM to recognize change

### ISSUE THREAD

**Issue by jwschmidt** [itsjavi/bootstrap-colorpicker#200] opened 2017-01-31 20:57 UTC
The way the code is not when using the picker and making a change the DOM will not trigger the onchange event. I have added this.input.change(); into the mouseup section to trigger the onchange event.

**Comment by itsjavi** [comment] 2017-02-02 10:46
duplicate of #192

**Closed by itsjavi** 2017-02-02 10:46 UTC
Labels: duplicate
