### ISSUE TITLE
autoInputFallback=false converts #ff0 to #ffff00 but I wasn't done typing yet

### ISSUE THREAD

**Issue by DianaKoenraadt** [itsjavi/bootstrap-colorpicker#318] opened 2020-08-19 09:06 UTC
### Description

`autoInputFallback`=false coerces my input before I've finished typing.

### Context

- bootstrap-colorpicker version: latest
- bootstrap version: latest
- jQuery version: 3.5.1
- Browser name and version: Chrome
- Operative System name an version: WIndows

### Expected behavior

To be able to type 6-digit hex code by hand.

### Actual behavior

After 3 hex digits, the input is converted to 6 digits. I can't type my 6-digit hex code.

### Live Example

https://jsfiddle.net/gqyfsmrb/1/

**Comment by itsjavi** [comment] 2021-04-23 20:07
This is a duplicate of #323 and will be handled there

**Closed by itsjavi** 2021-04-23 20:07 UTC
